{% set name = "puccinialin" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/puccinialin-{{ version }}.tar.gz
  sha256: 30480edcfbf02dbc20581d7e08b86db298f97794593ecd28c22b8b1a0f40cfd9

build:
  entry_points:
    - puccinialize = puccinialin.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core
    - pip
  run:
    - python >={{ python_min }}
    - filelock >=3.19.1,<4.0.0
    - httpx >=0.28.1,<0.29
    - platformdirs >=4.3.6,<5
    - tqdm >=4.67.1,<5

test:
  imports:
    - puccinialin
  commands:
    - pip check
    - puccinialize --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/puccinialin
  summary: Install rust into a temporary directory for boostrapping a rust-based build backend
  license: Apache-2.0 AND MIT
  license_file:
    - license-mit
    - license-apache
  dev_url: https://github.com/konstin/puccinialin

extra:
  recipe-maintainers:
    - shermansiu
